<a href="https://colab.research.google.com/github/mattsdata/UniPython/blob/master/NumpyPractise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6,)],[(3,2,1), (4,5,6)]], dtype = float)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

In [ ]:
d=np.zeros((3,4))  #Create an array of zeros
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
d=np.ones((2,3,4),dtype=np.int16) #Create an array of ones
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
d = np.arange(10,25,5)  #Create an array of evenly spaced values (step value)
d

array([10, 15, 20])

In [ ]:
d=np.linspace(0,2,9)    #Create an array of evenly spaced values (number of samples)
d

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
e = np.full((2,2),7) #Create a constant array
e

array([[7, 7],
       [7, 7]])

In [ ]:
f = np.eye(2) #Create a 2X2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [ ]:
g=np.random.random((2,2)) #Create an array with random values
g

array([[0.12309748, 0.47187311],
       [0.14524284, 0.00646629]])

In [ ]:
h=np.empty((3,2))  #Create an empty array
h

In [ ]:
np.info(np.ndarray.dtype)

In [ ]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [ ]:
c.shape #b.shape c.shape

(2, 2, 3)

In [ ]:
len(c)

2

In [ ]:
c.sum()

42.5

In [ ]:
c.mean()

3.5416666666666665

12.0
